Добавлено сбалансированное удаление в RB Tree
spbu-coding-2022/trees-2 pull request #26
Opened 2023-04-07 08:33 UTC by Parzival-05

Добавлено сбалансированное удаление в RB Tree
RB Tree готов! (Если без багов...)

2023-04-07 08:48 UTC, osogi commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +        return blackHeightVar
Может тут возвращать `blackHeightVar + 1`, так как листья черные?

2023-04-07 08:48 UTC, osogi commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +                rightChild.col = RBNode.Colour.BLACK
Ситуация: удалили черную ноду у которой ребенок тоже черный. Черная высота поменялась, а так как ребенок тоже черный, то его покраска в черны не изменит черную высоту.

2023-04-07 08:53 UTC, osogi commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> -            }
А почему это невозможный кейс? Допустим у нас дерево
```
   40
  /  \
20   null
```
И мы удаляем из него 40

2023-04-07 08:54 UTC, Parzival-05 commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +        return blackHeightVar
Нет разницы, +1 или +0: так как у всех  черная высота считается одинаково, проблем не будет.

2023-04-07 08:55 UTC, osogi commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +        return blackHeightVar
Да, но.... А это приватная функция, ок вопросов нет

2023-04-07 08:59 UTC, osogi commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +        return 0
А зачем везде `return 0`?

2023-04-07 09:00 UTC, Parzival-05 commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +                rightChild.col = RBNode.Colour.BLACK
Пример?

2023-04-07 09:07 UTC, Parzival-05 commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +        return 0
Чтобы выйти, когда нужно

2023-04-07 09:17 UTC, osogi commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> +        return 0
Тогда можно сделать функцию без возврата значения и просто писать `return`

2023-04-07 09:29 UTC, Parzival-05 commented on binaryTree/src/main/kotlin/org/tree/binaryTree/RBTree.kt
> -            }
Спасибо!

2023-04-07 09:38 UTC, osogi approved these changes

2023-04-09 08:50 UTC, osogi requested changes
Подтяните сначала фиксы
https://github.com/spbu-coding-2022/trees-2/pull/30

2023-04-10 18:15 UTC, Anna-er approved these changes

2023-04-11 10:53 UTC, osogi approved these changes

2023-04-11 11:02 UTC, merged